### ISSUE TITLE
Errors while compiling on Mac OS

### ISSUE THREAD

**Issue by schmidt9** [Urban82/Aes256#1]
Getting errors, changing to `fseeko` fixed errors
`[ 25%] Built target aes256
[ 37%] Building CXX object utils/CMakeFiles/decrypt.dir/decrypt.cpp.o
use of undeclared identifier 'fseeko64'; did
      you mean 'fseeko'?
    fseeko64(input, 0, SEEK_END);
    ^~~~~~~~
    fseeko
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/stdio.h:420:6: note: 
      'fseeko' declared here
int      fseeko(FILE * __stream, off_t __offset, int __whence);
         ^
utils/decrypt.cpp:67:5: error: use of undeclared identifier 'fseeko64'; did
      you mean 'fseeko'?
    fseeko64(input, 0, SEEK_SET);
    ^~~~~~~~
    fseeko
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/stdio.h:420:6: note: 
      'fseeko' declared here
int      fseeko(FILE * __stream, off_t __offset, int __whence);
         ^
2 errors generated.
`

**Comment by Urban82** [comment]
@schmidt9 just let me know if this fixes your issue. I don't have apple platform to test it.

**Comment by schmidt9** [comment]
@Urban82 thanks it worked
