### ISSUE TITLE
Encrypted text can't be decrypted

### ISSUE THREAD

**Issue by hainzhao** [Urban82/Aes256#10]
I tried to use the function to encrypt the data "12345678", most of the time the encrytped value can be decrypted without any issue, but some times it can not be decrypted. So I wrote a simple test program and found that around 5% of keys, the value can't be decrypted. Below are some sample key values:

FfNgVd   
SVZjcv
KvuiaK
9nJtTj

**Comment by Urban82** [comment]
Sorry, but I cannot reproduce your issue:

```
echo -n "12345678" > /tmp/foo
for KEY in FfNgVd SVZjcv KvuiaK 9nJtTj; do
  echo "KEY: $KEY"
  ./encrypt "$KEY" "/tmp/foo" "/tmp/foo.$KEY"
  ./decrypt "$KEY" "/tmp/foo.$KEY" "/tmp/foo.$KEY.decrypted"
  diff "/tmp/foo" "/tmp/foo.$KEY.decrypted"
done
```

```
KEY: FfNgVd
File is 8 bytes
Read 8 bytes
File is 43 bytes
Read 43 bytes
KEY: SVZjcv
File is 8 bytes
Read 8 bytes
File is 43 bytes
Read 43 bytes
KEY: KvuiaK
File is 8 bytes
Read 8 bytes
File is 43 bytes
Read 43 bytes
KEY: 9nJtTj
File is 8 bytes
Read 8 bytes
File is 43 bytes
Read 43 bytes
```

there are no differences between the original file (`/tmp/foo`) and all decrypted files (`/tmp/foo.*.decrypted`)

**Comment by HainanZhao** [comment]
Sorry, the library is totally fine. It's one of my base64 encoding functions that is causing the issue. Thanks for the quick reply.
