### ISSUE TITLE
Use the library to decrypt node.js crypto encryption

### ISSUE THREAD

**Issue by biboc** [Urban82/Aes256#11]
Hi,

It's not an issue to this library but an help on how to use it with node.js encryption
Here is the node.js code to encrypt a word
```
const algorithm = 'aes256';
var wordToEncrypt = 'super';
var key = '8TRAMRJ7iYX2yJsdq';
var cipher = crypto.createCipher(algorithm, key);
var crypted = cipher.update(wordToEncrypt, 'utf8', 'hex');
crypted += cipher.final('hex');
console.log(crypted)
```
Result is: cd0575308dc1f0accba7392b46953889

C++ code using Aes256 lib:
```
#include <aes256.hpp>

std::string key = "8TRAMRJ7iYX2yJsdq";
std::string crypted = "cd0575308dc1f0accba7392b46953889";

ByteArray key;
for (unsigned char i = 0; i < houseId.length(); i++) key.push_back(houseId[i]);

unsigned char enc[username.length()];
ByteArray dec;
for (unsigned char i = 0; i < username.length(); ++i) {
    enc[i] = username[i];
}

ByteArray::size_type dec_len = Aes256::decrypt(key, enc, username.length(), dec);

for (unsigned char i = 0; i < dec_len; ++i) {
    std::cout << dec[i] << " ";
}
std::cout << std::endl;
```

Result is not 'super"

What am I doing wrong?

**Comment by Urban82** [comment]
Hi,

first of all, ByteArray must contain bytes, while your string is HEX encoded: this means that you should convert every couple of characters with the corresponding byte before inserting it in the ByteArray.

anyway: the encoded data from this library is not 100% standard as it has a header part that contains extra data (mainly the salt and it's size), so the library can decode only data that were encoded by the library itself (in the project where it was used when I wrote it I just needed for something to encode and decode data from the project itself and not from external tools, so I didn't payed too attention to make it working with standard tools!)
