### ISSUE TITLE
'register' warnings

### ISSUE THREAD

**Issue by schmidt9** [Urban82/Aes256#3]
Hi
In XCode using C++11 I get warnings  in aes256.cpp: `'register' storage class specifier is deprecated and incompatible with C++1z`
Do you really need this obsolete specifier?
If yes we could eliminate this warning by adding to aes256.cpp (sorry cannot create a pull request now)
```
#if __cplusplus > 199711L
#define register      // Deprecated in C++11.
#endif  // #if __cplusplus > 199711L
```

**Comment by Urban82** [comment]
The library is not thought with C++11 in mind. The **register** keyword is only an hint, but if the compiler honor it, the execution gain in speed.
The keyword is used only in the cpp file and not in the header, so you can compile the library without C++11 and than compile your code that include the header and link the library with C++11 or newer without any problem.

**Comment by schmidt9** [comment]
I got you, I don't use compiled library though and include aes256.hpp and aes256.cpp directly into the project, that's why I get this warning. By the way I also noticed that compiled utils "encode" and "decode" depend on compiled library being tied to its path, and if I remove the lib or change the path, the utils stop working. That's why I compile them manually like that to make them independent
```
#!/bin/sh
g++ -include aes256.cpp -Wall -O2 -o encrypt encrypt.cpp
g++ -include aes256.cpp -Wall -O2 -o decrypt decrypt.cpp
```
