### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by PonasKovas** [Urban82/Aes256#5]
Hey. I'm sorry but I really don't get it.
I tried including `aes256.hpp` in my main, and then compiling `aes.cpp` and `main.cpp` together, then in inside the main, i tried `Aes256::encrypt(key,plain,encrypted)` but what the hell is `ByteArray`? How do I convert my key and plain-text (which are Strings) to `ByteArrays`? And also, why doesn't the encrypt function just return the encrypted value, instead of changing argument `encrypted`?

**Comment by Urban82** [comment]
As you can see from `aes256.hpp`, `ByteArray` is just a typedef for `std::vector<unsigned char>`.

The methods don't return the encrypted value because they return the encrypted size as this library was derived from another project that needed that value.
