### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PatSpiegel** [Urban82/Aes256#9]
Can u say "initialization vector" iv ?

**Comment by Urban82** [comment]
Sorry, but I don't understand what is the issue here? Can you explain it, please?

**Comment by PatSpiegel** [comment]
I need "Initialization Vector" so that I can [encrypt files in php](https://www.php.net/manual/en/function.openssl-encrypt.php), and decrypt already in C ++ using your library

**Comment by Urban82** [comment]
Everything you need is in the file [aes256.cpp](https://github.com/Urban82/Aes256/blob/master/src/aes256.cpp).
